/**
 * 
 * 
 * @author ftl
 *
 */
package com.fiberhome.smartas.demo;

import java.util.Date;

import com.fiberhome.smartas.core.model.LongIdVO;

public class Test extends LongIdVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smartas..tpl_temp_t.name
     *
     * @generated Tue Mar 15 11:21:25 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smartas..tpl_temp_t.test
     *
     * @generated Tue Mar 15 11:21:25 CST 2016
     */
    private Date test;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smartas..tpl_temp_t.name
     *
     * @return the value of smartas..tpl_temp_t.name
     *
     * @generated Tue Mar 15 11:21:25 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smartas..tpl_temp_t.name
     *
     * @param name the value for smartas..tpl_temp_t.name
     *
     * @generated Tue Mar 15 11:21:25 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smartas..tpl_temp_t.test
     *
     * @return the value of smartas..tpl_temp_t.test
     *
     * @generated Tue Mar 15 11:21:25 CST 2016
     */
    public Date getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smartas..tpl_temp_t.test
     *
     * @param test the value for smartas..tpl_temp_t.test
     *
     * @generated Tue Mar 15 11:21:25 CST 2016
     */
    public void setTest(Date test) {
        this.test = test;
    }
}
